### ISSUE TITLE
Determining effective training

### ISSUE THREAD

**Issue by dboshardy** [yuval-alaluf/restyle-encoder#64]
I'm trying to train a model based off a stylegan i trained similar to toonify.  

I'm attempting to train the restyle-pSp model on this dataset and ffhq for the translation task.  However, after quite a long time (can't set batch size at 8 due to GPU memory running out despite running with a 16GB of VRAM), the loss isn't really changing (see below):

I'm training using the following options:
```yaml
batch_size: 6
board_interval: 50
checkpoint_path: null
dataset_type: "my_ffhq_dataset"
encoder_type: "BackboneEncoder"
exp_dir: "experiment/restyle_psp"
id_lambda: 1
image_interval: 100
input_nc: 6
l2_lambda: 1
learning_rate: 0.0001
lpips_lambda: 0.8
max_steps: 500000
moco_lambda: 0
n_iters_per_batch: 5
optim_name: "ranger"
output_size: 1024
save_interval: 2000
start_from_latent_avg: true
stylegan_weights: "../models/model.pt"
test_batch_size: 2
test_workers: 2
train_decoder: false
val_interval: 1000
w_norm_lambda: 0.25
workers: 4
```

The below metrics are what they looked like after only 1k iterations. And looking at the model output in the experiment dir, the output faces aren't changing in the slightest.  The source and target are appropriately configured as they are the normal and the toon version of the normal face.  It's a dataset of 1024x1024 in 3500 pairs for training and 1500 for testing.
```shell
Metrics for train, step 20900
        loss_id =  0.44862064719200134
        id_improve =  0.47951146960258484
        loss_l2 =  0.09637744724750519
        loss_lpips =  0.4569443166255951
        loss_w_norm =  0.0013350744266062975
        loss =  0.9108873605728149
Metrics for train, step 20950
        loss_id =  0.5060080885887146
        id_improve =  0.322285289876163
        loss_l2 =  0.09358177334070206
        loss_lpips =  0.4740564227104187
        loss_w_norm =  0.0016432201955467463
        loss =  0.9792457818984985
Metrics for train, step 21000
        loss_id =  0.4523411691188812
        id_improve =  0.38620127489169437
        loss_l2 =  0.12004581093788147
        loss_lpips =  0.44153523445129395
        loss_w_norm =  0.0012316436041146517
        loss =  0.9259231090545654
```
